name: Build Code
on: 
  workflow_dispatch:
  push:
    branches:
      - main
      - samples/*
      - test

jobs:
  code-build:
    runs-on: ubuntu-latest
    steps:
      - name: code-checkout
        uses: actions/checkout@v4
        with:
          ref: 'samples/album-app'

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'

      - name: build
        run: ./gradlew build

    
